/*
 * Utility functions for trap handling in Supervisor mode.
 */

#include "riscv.h"
#include "process.h"
#include "strap.h"
#include "syscall.h"
#include "string.h"

#include "spike_interface/spike_utils.h"
#include "spike_interface/spike_file.h"

//
// handling the syscalls. will call do_syscall() defined in kernel/syscall.c
//
static void handle_syscall(trapframe *tf) {
  // tf->epc points to the address that our computer will jump to after the trap handling.
  // for a syscall, we should return to the NEXT instruction after its handling.
  // in RV64G, each instruction occupies exactly 32 bits (i.e., 4 Bytes)
  tf->epc += 4;

  // 处理系统调用参数并获取返回值
  long ret = do_syscall(tf->regs.a0, tf->regs.a1, tf->regs.a2, tf->regs.a3,
                          tf->regs.a4, tf->regs.a5, tf->regs.a6, tf->regs.a7);
  tf->regs.a0 = ret; // 返回值写回 a0

}

//
// global variable that store the recorded "ticks". added @lab1_3
static uint64 g_ticks = 0;
//
// added @lab1_3
//
void handle_mtimer_trap() {
  sprint("Ticks %d\n", g_ticks);
  g_ticks++;
  // 清除 SIP 寄存器的 SSIP 位
  write_csr(sip, read_csr(sip) & ~SIP_SSIP);
}

//
// added @lab1_challenge2: print the source file name and line number of the faulting instruction
//
void print_errorline(uint64 epc) {
  // look up the faulting address in the addr-line table
  int idx = -1;
  for (int i = 0; i < current->line_ind; i++) {
    if (current->line[i].addr > epc) {
      idx = i - 1;
      break;
    }
  }
  if (idx < 0) idx = current->line_ind - 1;

  if (idx >= 0 && current->line != NULL) {
    addr_line *al = &current->line[idx];
    code_file *cf = &current->file[al->file];
    char *dir = current->dir[cf->dir];
    char *filename = cf->file;

    // construct file path: dir/filename
    char filepath[256];
    if (dir != NULL && dir[0] != '\0') {
      int j = 0;
      while (*dir && j < 250) filepath[j++] = *dir++;
      filepath[j++] = '/';
      while (*filename && j < 254) filepath[j++] = *filename++;
      filepath[j] = '\0';
    } else {
      int j = 0;
      while (*filename && j < 254) filepath[j++] = *filename++;
      filepath[j] = '\0';
    }

    sprint("Runtime error at %s:%d\n", filepath, al->line);

    // read the source file and print the offending line
    spike_file_t *srcfile = spike_file_open(filepath, O_RDONLY, 0);
    if (!IS_ERR_VALUE(srcfile)) {
      // read enough of the source file
      char buf[4096];
      ssize_t nread = spike_file_pread(srcfile, buf, sizeof(buf) - 1, 0);
      spike_file_close(srcfile);

      if (nread > 0) {
        buf[nread] = '\0';
        // find the target line
        int cur_line = 1;
        char *p = buf;
        while (cur_line < (int)al->line && *p) {
          if (*p == '\n') cur_line++;
          p++;
        }
        if (cur_line == (int)al->line) {
          // find end of this line
          char *line_start = p;
          // skip leading whitespace for display, but we print with 2-space indent
          while (*p && *p != '\n') p++;
          *p = '\0';
          // skip leading whitespace from source
          char *trimmed = line_start;
          while (*trimmed == ' ' || *trimmed == '\t') trimmed++;
          sprint("  %s\n", trimmed);
        }
      }
    }
  }
}

//
// kernel/smode_trap.S will pass control to smode_trap_handler, when a trap happens
// in S-mode.
//
void smode_trap_handler(void) {
  // make sure we are in User mode before entering the trap handling.
  // we will consider other previous case in lab1_3 (interrupt).
  if ((read_csr(sstatus) & SSTATUS_SPP) != 0) panic("usertrap: not from user mode");

  assert(current);
  // save user process counter.
  current->trapframe->epc = read_csr(sepc);

  // if the cause of trap is syscall from user application.
  // read_csr() and CAUSE_USER_ECALL are macros defined in kernel/riscv.h
  uint64 cause = read_csr(scause);

  // we need to handle the timer trap @lab1_3.
  if (cause == CAUSE_USER_ECALL) {
    handle_syscall(current->trapframe);
  } else if (cause == CAUSE_MTIMER_S_TRAP) {  //soft trap generated by timer interrupt in M mode
    handle_mtimer_trap();
  } else {
    // lab1_challenge2: print source error line info before panicking
    print_errorline(current->trapframe->epc);

    switch (cause) {
      case CAUSE_ILLEGAL_INSTRUCTION:
        panic("Illegal instruction!");
        break;
      case CAUSE_MISALIGNED_FETCH:
        panic("Instruction address misaligned!");
        break;
      case CAUSE_FETCH_ACCESS:
        panic("Instruction access fault!");
        break;
      case CAUSE_LOAD_ACCESS:
        panic("Load access fault!");
        break;
      case CAUSE_STORE_ACCESS:
        panic("Store/AMO access fault!");
        break;
      case CAUSE_MISALIGNED_LOAD:
        panic("Misaligned Load!");
        break;
      case CAUSE_MISALIGNED_STORE:
        panic("Misaligned AMO!");
        break;
      case CAUSE_FETCH_PAGE_FAULT:
        panic("Instruction page fault!");
        break;
      case CAUSE_LOAD_PAGE_FAULT:
        panic("Load page fault!");
        break;
      case CAUSE_STORE_PAGE_FAULT:
        panic("Store/AMO page fault!");
        break;
      default:
        sprint("smode_trap_handler(): unexpected scause %p\n", read_csr(scause));
        sprint("            sepc=%p stval=%p\n", read_csr(sepc), read_csr(stval));
        panic("unexpected exception happened.\n");
        break;
    }
  }

  // continue (come back to) the execution of current process.
  switch_to(current);
}
